### ISSUE TITLE
Uncaught Error: This socket is closed.

### ISSUE THREAD

**Issue by xiuliren** [tinloaf/autocomplete-plus-python-jedi#18] opened 2015-05-02 22:16 UTC
[Enter steps to reproduce below:]
1. ...import numpy as np
2. ...np.

**Atom Version**: 0.196.0
**System**: linux 3.13.0-49-generic
**Thrown From**: [autocomplete-plus-python-jedi](https://github.com/tinloaf/autocomplete-plus-python-jedi) package, v0.3.0
### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
  at Socket._writeGeneric (net.js:634:19)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at JediProvider.getSuggestions (/usr/people/jingpeng/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-provider.coffee:222:14)
  at /usr/people/jingpeng/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:152:45
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/people/jingpeng/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:135:15)
  at AutocompleteManager.getSuggestionsFromProviders (/usr/people/jingpeng/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/people/jingpeng/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:129:6)
  at /usr/people/jingpeng/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```
### Commands

```
     -0:47.2.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode)
     -0:01.6.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {
    "projectHome": "/usr/people/jingpeng/workspace",
    "disabledPackages": [
      "autocomplete-plus-jedi"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-runner, v2.3.0
autocomplete-plus, v2.12.1
autocomplete-plus-python-jedi, v0.3.0
language-julia, v0.7.2
vim-mode, v0.45.0

# Dev
No dev packages
```

**Comment by tinloaf** [comment] 2015-05-03 08:50
I'm afraid I cannot reproduce this. If you can, could you open the development console (Ctrl-Shift-i) right after this happened? You should see a list of errors, some of them containing python backtraces. Could you post these here?

**Comment by blaggacao** [comment] 2015-05-03 19:17
same error. Windows8.1.
It happens when typing a single space into a new file named `test` with following settings at the down right: `UTF-8` and marked as `Python`

**Comment by borzunov** [comment] 2015-05-04 09:34
I've encountered the same error on Ubuntu 14.04 LTS since I've installed this package (about version v0.2.4). The error occurred during any actions when autocomplete must appear (on creating a new file or editing existing one) even if all community packages except `autocomplete-plus` and `autocomplete-plus-python-jedi` are disabled.

But when I started writing this report I found a possible solution: I tried to reinstall `jedi` packages from Ubuntu repositories (they have version 0.7.0-1 here) to the latest versions from PyPI (v0.9.0) and the package started to work well. Nevertheless, this report may be helpful for you.

_The screenshot with the backtraces:_
![screenshot from 2015-05-04 14 05 16](https://cloud.githubusercontent.com/assets/8748943/7451355/44305f58-f269-11e4-9047-30f53a440132.png)

**Comment by tinloaf** [comment] 2015-05-04 11:56
@borzunov D'Oh. That was stupid, there was an error in the error handling code itself... I fixed that in 0.3.1. Could you update to 0.3.1 and try to re-trigger this bug? The traceback in the console should be way more meaningful then.

You could do so by activating a virtualenv in which you installed jedi 0.7.0-1?

**Comment by tinloaf** [comment] 2015-05-04 14:06
Gotcha. I could reproduce this with Jedi 0.7. You shouldn't be using it, since it has no support for docstrings (which crashed the plugin).

This should be fixed in version 0.3.2. Feel free to re-open if it's not!

**Comment by danqing** [comment] 2015-08-04 22:23
Just saw this error.

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [autocomplete-plus-python-jedi](https://github.com/tinloaf/autocomplete-plus-python-jedi) package, v0.3.6

### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
    at Socket._writeGeneric (net.js:634:19)
    at Socket._write (net.js:687:8)
    at doWrite (_stream_writable.js:295:12)
    at writeOrBuffer (_stream_writable.js:282:5)
    at Socket.Writable.write (_stream_writable.js:210:11)
    at Socket.write (net.js:612:40)
    at JediProvider.getSuggestions (/Users/danqing/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-provider.coffee:320:18)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -9:59.3.0 core:paste (atom-text-editor.editor.is-focused)
     -9:55.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:00.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:36.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:36 core:backspace (atom-text-editor.editor.is-focused)
     -0:35.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:32.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:25.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:02.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.9.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-tree-view"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.28.8
autocomplete-plus-python-jedi, v0.3.6
file-icons, v1.6.2
go-plus, v3.4.4
jshint, v1.3.10
language-jade, v0.6.2
language-protobuf, v0.5.0
language-swift, v0.4.0
language-thrift, v1.0.1
pigments, v0.9.3

# Dev
No dev packages
```

**Comment by danqing** [comment] 2015-08-04 22:28
I doubt that it will help, but the code snippet is the following:

``` py
def test_oneoff(self):
    uri_template = '/some-path'
    email = "redacted@whatever.com"
    start = "20150701"
    end = "20150703"
    headers = {HEADER_KEY: SOME_HEADER}
    self.get(
        uri_template.format(email, start, end), 
        headers=headers, 
        expected_status=200
    )

def test_oneoff

def test_register(self):
```

I was working on the second `def test_oneoff` line, and whenever I enter a letter, the error shows up once. Enter another letter, the error shows up again.

**Comment by tinloaf** [comment] 2015-09-24 12:36
Hi! I'm sorry to reply so late, but I had hoped that this problem would vanish on it's own: This plugin has long been abandoned in favor of https://github.com/sadovnychyi/autocomplete-python ..

The Atom folks wanted to somehow mark my plugin as deprecated, but have not done so yet, as it seems. So, please switch over to that other one!

**Closed as completed by tinloaf** 2015-09-24 12:36 UTC
